services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - auth_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d user_db -U username" ]
      interval: 10s
      timeout: 5s
      retries: 5

  user_service:
    build: ./user_service
    environment:
      - DATABASE_URL=postgres://username:password@db:5432/user_db
    volumes:
      - ./user_service/signature.pem:/tmp/signature.pem
      - ./user_service/signature.pub:/tmp/signature.pub
    command: [ "--private", "/tmp/signature.pem", "--public", "/tmp/signature.pub", "--kafka", "kafka:9093", "--port", "8081" ]
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    networks:
      - auth_network
      - proxy_network
      - kafka_network
  
  cassandra:
    image: cassandra:latest
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_LISTEN_ADDRESS=auto
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=my-datacenter-1f
    volumes:
      - cassandra_data:/var/lib/cassandra:rw
    ports:
      - "7000:7000"
      - "9042:9042"
    networks:
      - post_network
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 10s
      timeout: 5s
      retries: 10

  post_service:
    build: ./post_service
    command: ["--cassandra", "cassandra:9042",  "--kafka", "kafka:9093", "--port", "8082"]
    depends_on:
      - cassandra
      - kafka
    ports:
      - "8082:8082"
    networks:
      - post_network
      - proxy_network
      - kafka_network

  proxy_service:
    build: ./proxy_service
    volumes:
      - ./user_service/signature.pub:/tmp/signature.pub
    command: ["--post", "http://post_service:8082","--user", "http://user_service:8081", "--public", "/tmp/signature.pub", "--port", "8080"]
    depends_on:
      - user_service
      - post_service
      - kafka
    ports:
      - "8080:8080"
    networks:
      - proxy_network

  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka_network

  kafka-ui:
    image: kafbat/kafka-ui:main
    ports:
      - "8079:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    depends_on:
      - kafka
    networks:
      - kafka_network

volumes:
  postgres_data:
  cassandra_data:

networks:
  auth_network:
  post_network:
  proxy_network:
  kafka_network:
