services:
  test_db:
    image: postgres:13
    environment:
      POSTGRES_USER: test_username
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_user_db
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d test_user_db -U test_username" ]
      interval: 10s
      timeout: 5s
      retries: 5
