[package]
name = "reaction_service"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.13"
prost = "0.13"
prost-types = "0.13"
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
clap = {version = "4.5.23", features = ["derive"]}
clickhouse = { version = "0.13.2", features = ["uuid", "time", "chrono", "test-util"]}
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
futures = "0.3"

[build-dependencies]
tonic-build = "*"
